[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma generate && npx prisma db push --accept-data-loss && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10